modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/bibliotheca/issues"

[[mods]]
modId="bibliotheca"
displayName="Bibliotheca"
version="${file.jarVersion}"
authors="Ewy"
credits="Credits to LuHiGi for helping me with tons of stuff"
description='''
Open-source library mod to make my life a bit easier cause I am lazy.
'''

[[dependencies.bibliotheca]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.+,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bibliotheca]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.+,)"
    ordering="NONE"
    side="BOTH"